### ISSUE TITLE
the phylip sequence matrix 

### ISSUE THREAD

**Issue by YanTingNiu** [simjoly/jml#2]
I input only one species one  sequence not sampling populations.
and there report issues:

 *** Species trees file information ***
 Number of trees read: 20002
 Number of trees in burnin: 5000
 Number of trees post-burnin: 15002
 Number of trees sampled for simulations: 15002
 Seed used: 12345
 Significance level: 0.1

 *** Locus-specific information ***
 Locus relative mutation rate: 0.8762
 Locus heredity scalar: 1

 Performing simulation 1Segmentation fault (core dumped)
I wonder wether there must be population datasets?

**Comment by simjoly** [comment]
Sorry, I haven't read your comment before.
I am not sure what causes the problem, but it might actually be because there is a single species. Try to analyze at least two species.
